// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znnoikoadvhqlrgugicl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpubm9pa29hZHZocWxyZ3VnaWNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNzg2OTAsImV4cCI6MjA2Mzk1NDY5MH0.4vZFlKre7NBLBJOVSqFPNB5KjoTXtDzpejbFRQedeTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);