// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdzegtuwjhykvdfsroxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kemVndHV3amh5a3ZkZnNyb3hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNzYxNDEsImV4cCI6MjA2Mzk1MjE0MX0.81Ao1Up7xyBdjGMzE0vosv61ds7Y1FHOqOO3QXB9ZM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);